
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkmaxidkfmiyvyyiabix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrbWF4aWRrZm1peXZ5eWlhYml4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NTY0MjQsImV4cCI6MjA2MzIzMjQyNH0.CwGeGCd8tKithITZnY9gFHl9a9eICYIU-mqPOqebskI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
